/* SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright (C) 2018-2019 Arm Ltd.
 * Author: Vincent Stehlé <vincent.stehle@arm.com>
 */

#ifndef REVERE_HW_H_INCLUDED
#define REVERE_HW_H_INCLUDED

#include <stdint.h>

#define __packed __attribute__ ((packed))
typedef uint64_t u64;
#include "revere.h"

/* Some handy aliases */
#define AMU_AIDR	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_AMU_AIDR_OFFSET)
#define AMU_CR		(RVR_MANAGEMENT_PAGE_OFFSET + RVR_AMU_CR_OFFSET)
#define AMU_CR_EN	(RVR_AMU_CR_AMU_EN_MASK << RVR_AMU_CR_AMU_EN_SHIFT)
#define AMU_IDR		(RVR_MANAGEMENT_PAGE_OFFSET + RVR_AMU_IDR_OFFSET)
#define AMU_IIDR	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_AMU_IIDR_OFFSET)
#define CMD_BASE_PTR	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_BASE_PTR_OFFSET)
#define CMD_CTRL	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_CTRL_OFFSET)

#define RESP_BASE_PTR	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_BASE_PTR_OFFSET +\
			0x10)

#define RESP_CTRL	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_CTRL_OFFSET +\
			0x10)

#define EXC_BASE_PTR	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_BASE_PTR_OFFSET +\
			0x20)

#define EXC_CTRL	(RVR_MANAGEMENT_PAGE_OFFSET + RVR_MSK_CTRL_OFFSET +\
			0x20)

#define CMD_READ_INDEX	(RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_READ_INDEX_TX0_OFFSET)

#define CMD_WRITE_INDEX	(RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_WRITE_INDEX_TX0_OFFSET)

#define RESP_READ_INDEX	(RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_READ_INDEX_RX0_OFFSET)

#define RESP_WRITE_INDEX (RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_WRITE_INDEX_RX0_OFFSET)

#define EXC_READ_INDEX	(RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_READ_INDEX_RX1_OFFSET)

#define EXC_WRITE_INDEX (RVR_MANAGEMENT_PAGE_OFFSET +\
			RVR_MGT_WRITE_INDEX_RX1_OFFSET)

#define LOG2_MSG_LENGTH_SHIFT RVR_MSK_CTRL_LOG2_MSG_LENGTH_SHIFT

/* The following offsets are inside one AMI */
#define AMI_SW0		RVR_AMI_SW_PAGE_0_OFFSET
#define READ_INDEX_RX0	RVR_READ_INDEX_RX0_OFFSET
#define READ_INDEX_TX0	RVR_READ_INDEX_TX0_OFFSET
#define TX_DIGEST	RVR_TX_DIGEST_OFFSET
#define TX_DIGEST_MASK	RVR_TX_DIGEST_MASK_OFFSET
#define RX_DIGEST	RVR_RX_DIGEST_OFFSET
#define RX_DIGEST_MASK	RVR_RX_DIGEST_MASK_OFFSET
#define WRITE_INDEX_RX0	RVR_WRITE_INDEX_RX0_OFFSET
#define WRITE_INDEX_TX0	RVR_WRITE_INDEX_TX0_OFFSET

#endif /* REVERE_HW_H_INCLUDED */
